;;;; Emacs Bookmark Format Version 1;;;; -*- coding: utf-8-emacs; mode: lisp-data -*-
;;; This format is meant to be slightly human-readable;
;;; nevertheless, you probably don't want to edit it.
;;; -*- End Of Bookmark File Format Version Stamp -*-
(("org-capture-last-stored"
  (filename . "c:/Users/gabri/Documents/emacs-org/inbox.org")
  (front-context-string . "** TODO Finish t")
  (rear-context-string . "9-19 sáb 15:48]\n")
  (position . 55)
  (last-modified 27310 64658 710361 0))
)
